name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  Development:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev123.myapp.net/'
    steps:
      - name: Deploy
        run: echo Deploying to DEV environment!
        
  Staging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Development]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://staging.myapp.net'
    steps:
      - name: Deploy
        run: echo Deploying to STAGING environment!
        
  Production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [Staging]
    environment:
      name: Production
      url: 'http://myapp.net'
    steps:
      - name: Deploy
        run: echo Deploying to PRODUCTION environment!
    
